CUDA_VISIBLE_DEVICES=0 python main_train_mrg_dpo_beta.py \
    --image_dir /ssd/shilei/dataset/physionet.org/files/mimic-cxr-jpg/2.0.0/images \
    --ann_path data/mimic_cxr/FINAL2/SFT3/mimic_prefer_cliq_sft3_final.json \
    --dataset_name mimic_cxr \
    --gen_max_len 150 \
    --gen_min_len 100 \
    --batch_size 16 \
    --epochs 60 \
    --save_dir results/MODPO/CliQ_10000/SFT3 \
    --seed 42 \
    --init_lr 1e-5 \
    --min_lr 1e-6 \
    --warmup_lr 5e-7 \
    --weight_decay 0.05 \
    --warmup_steps 2000 \
    --cls_weight 1 \
    --clip_k 21 \
    --beam_size 3 \
    --beta 0.5 \
    --mrg_beta 1 \
    --dpo_beta 1 \
    --index 0 \
    --load_peft_1 /home/shilei/project/PromptMRG/results/MODPO/F1_10000/SFT2/model_best.pth \
    --load_peft_2 /home/shilei/project/PromptMRG/results/MODPO/GREEN_10000/SFT2/model_best.pth \
    --load_pretrained /ssd/shilei/dataset/PromptMRG/model/model_best.pth
